#!/usr/bin/env python3
"""Run a model under onnxruntime and keep every intermediate tensor.

    dump-fixtures.py model.onnx feeds.npz outdir/

Writes outdir/inputs/<name>.npy for each input, outdir/values/<n>.npy for every
node output, and outdir/manifest.sexp naming them in graph order.

This is the harness a port hangs off.  A model that is thousands of nodes deep
gives one bit of feedback at the end — the answer is wrong — and that is not
enough to debug an arithmetic mistake in node 900.  With a golden value for every
node, a wrong answer names the node that first diverged, which turns the whole
thing from a research problem into a list.

FEEDS.NPZ is the caller's business, because what a model wants fed to it is the
one thing this script cannot know.  It must also be a feed the model answers
DETERMINISTICALLY: anything that samples noise has to be neutralized on the way
in — a VITS voice scales both its noise sources by values passed in, so zeroing
those makes the graph a pure function without touching the weights.  The check
below proves determinism rather than assuming it: two runs must agree bit for
bit, or the fixtures are not fixtures.  Whoever writes feeds.npz owns that.
"""
import sys
from pathlib import Path

import numpy as np
import onnx
import onnxruntime as ort


def expose_all_values(model):
    """Every node output becomes a graph output, so one run yields all of them."""
    g = model.graph
    have = {o.name for o in g.output}
    for n in g.node:
        for o in n.output:
            if o and o not in have:
                g.output.extend([onnx.ValueInfoProto(name=o)])
                have.add(o)
    return [o.name for o in g.output]


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    src, feedfile, outdir = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    (outdir / "values").mkdir(parents=True, exist_ok=True)
    (outdir / "inputs").mkdir(parents=True, exist_ok=True)

    with np.load(feedfile) as z:
        feeds = {k: z[k] for k in z.files}

    model = onnx.load(str(src))
    # the model's own outputs, before every intermediate joins them — the first
    # of these is what the determinism check watches
    declared = [o.name for o in model.graph.output]
    names = expose_all_values(model)

    so = ort.SessionOptions()
    # optimization would fuse and reorder the very nodes being dumped
    so.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
    sess = ort.InferenceSession(model.SerializeToString(), so,
                                providers=["CPUExecutionProvider"])

    outs = sess.run(names, feeds)
    watch = declared[0]
    ref = outs[names.index(watch)]
    if not np.array_equal(ref, sess.run([watch], feeds)[0]):
        raise SystemExit(f"{watch} differs between two runs of the same feed — these "
                         f"would not be fixtures; find the noise source and neutralize "
                         f"it in {feedfile} first")

    manifest = []
    for i, (nm, val) in enumerate(zip(names, outs)):
        val = np.asarray(val)
        np.save(outdir / "values" / f"{i}.npy", val)
        manifest.append((i, nm, str(val.dtype), list(val.shape)))

    # one .npy per input, so the Lisp gate feeds the model the same bytes
    # onnxruntime saw without needing a zip reader to find out what they were
    for k, v in feeds.items():
        np.save(outdir / "inputs" / f"{k}.npy", v)

    with open(outdir / "manifest.sexp", "w") as f:
        f.write(";;; Generated by mill's tools/dump-fixtures.py — do not edit.\n")
        f.write(f'(:model "{src.name}"\n')
        f.write(f" :outputs ({' '.join(chr(34) + n + chr(34) for n in declared)})\n")
        f.write(" :values (\n")
        for i, nm, dt, shape in manifest:
            f.write(f'  ({i} "{nm}" "{dt}" ({" ".join(str(s) for s in shape)}))\n')
        f.write("))\n")

    total = sum((outdir / "values" / f"{i}.npy").stat().st_size for i, *_ in manifest)
    print(f"{len(manifest)} values, {total/1e6:.0f} MB")
    print(f"{watch}: {ref.shape} {ref.dtype}")


if __name__ == "__main__":
    main()
